const express = require('express');
const auth = require('../modules/auth');
const category = require('../modules/categories');
const products = require('../modules/products');
const warehouse=require('../modules/warehouse');
const branchs=require('../modules/branchs');
const inventory=require('../modules/inventories');
const imports=require('../modules/imports');
const cart=require('../modules/cart');
const orders=require('../modules/order');
const payments=require('../modules/payments');
const profiles=require('../modules/profiles');
const router = express.Router();

router.use('/auth', auth);
router.use('/categories', category);
router.use('/products', products);
router.use('/payments', payments);
router.use('/warehouses', warehouse);
router.use('/branchs', branchs);
router.use('/inventory', inventory);
router.use('/imports', imports);
router.use('/cart', cart);
router.use('/orders', orders);
router.use('/profiles', profiles);
module.exports = router;
