const USER_STATUS = {
  ACTIVE:   'ACTIVE',
  INACTIVE: 'INACTIVE',
  BANNED:   'BANNED',
};

const USER_STATUS_VALUES = Object.values(USER_STATUS);

const ACTIVE_STATUS = {
  ACTIVE:   'ACTIVE',
  INACTIVE: 'INACTIVE',
};

const ACTIVE_STATUS_VALUES = Object.values(ACTIVE_STATUS);

const PRODUCT_STATUS = {
  ACTIVE:       'ACTIVE',
  INACTIVE:     'INACTIVE',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
};

const PRODUCT_STATUS_VALUES = Object.values(PRODUCT_STATUS);

const CUSTOMER_PRODUCT_STATUS = {
  AVAILABLE:    'AVAILABLE',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
};

const WAREHOUSE_TYPE = {
  MAIN:   'MAIN',
  BRANCH: 'BRANCH',
};

const WAREHOUSE_TYPE_VALUES = Object.values(WAREHOUSE_TYPE);

const ORDER_STATUS = {
  PENDING:   'PENDING',
  CONFIRMED: 'CONFIRMED',
  PACKING:   'PACKING',
  SHIPPING:  'SHIPPING',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
};

const ORDER_STATUS_VALUES = Object.values(ORDER_STATUS);

const STAFF_ORDER_UPDATE_STATUS_VALUES = [
  ORDER_STATUS.PACKING,
  ORDER_STATUS.SHIPPING,
  ORDER_STATUS.DELIVERED,
];

const ORDER_STATUS_TRANSITIONS = {
  [ORDER_STATUS.CONFIRMED]: ORDER_STATUS.PACKING,
  [ORDER_STATUS.PACKING]:   ORDER_STATUS.SHIPPING,
  [ORDER_STATUS.SHIPPING]:  ORDER_STATUS.DELIVERED,
};

const TRANSFER_STATUS = {
  PENDING:   'PENDING',
  APPROVED:  'APPROVED',
  REJECTED:  'REJECTED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

const TRANSFER_STATUS_VALUES = Object.values(TRANSFER_STATUS);

const SHIFT_STATUS = {
  OPEN:   'OPEN',
  CLOSED: 'CLOSED',
};

const SHIFT_STATUS_VALUES = Object.values(SHIFT_STATUS);

const ORDER_PAYMENT_METHOD = {
  COD:      'COD',
  CARD:     'CARD',
  TRANSFER: 'TRANSFER',
  MOMO:     'MOMO',
  VNPAY:    'VNPAY',
};

const ORDER_PAYMENT_METHOD_VALUES = Object.values(ORDER_PAYMENT_METHOD);

const POS_PAYMENT_METHOD = {
  CASH:     'CASH',
  CARD:     'CARD',
  TRANSFER: 'TRANSFER',
  MOMO:     'MOMO',
  VNPAY:    'VNPAY',
};

const POS_PAYMENT_METHOD_VALUES = Object.values(POS_PAYMENT_METHOD);

const PAYMENT_METHOD = {
  CASH:     'CASH',
  CARD:     'CARD',
  TRANSFER: 'TRANSFER',
  MOMO:     'MOMO',
  VNPAY:    'VNPAY',
  COD:      'COD',
};

const PAYMENT_METHOD_VALUES = Object.values(PAYMENT_METHOD);

const PAYMENT_STATUS = {
  PENDING:  'PENDING',
  PAID:     'PAID',
  SUCCESS:  'SUCCESS',
  FAILED:   'FAILED',
  REFUNDED: 'REFUNDED',
};

const PAYMENT_STATUS_VALUES = Object.values(PAYMENT_STATUS);

const WAREHOUSE_TRANSACTION_TYPE = {
  IMPORT:           'IMPORT',
  EXPORT:           'EXPORT',
  TRANSFER_OUT:     'TRANSFER_OUT',
  TRANSFER_IN:      'TRANSFER_IN',
  POS_SELL:         'POS_SELL',
  ONLINE_ORDER:     'ONLINE_ORDER',
  FAULTY_REPORT:    'FAULTY_REPORT',
  FAULTY_RESOLVE:   'FAULTY_RESOLVE',
  STOCKTAKE_ADJUST: 'STOCKTAKE_ADJUST',
};

const PRODUCT_AVAILABILITY_FILTERS = {
  ALL:          'all',
  AVAILABLE:    CUSTOMER_PRODUCT_STATUS.AVAILABLE,
  OUT_OF_STOCK: CUSTOMER_PRODUCT_STATUS.OUT_OF_STOCK,
};

module.exports = {
  USER_STATUS,
  USER_STATUS_VALUES,
  ACTIVE_STATUS,
  ACTIVE_STATUS_VALUES,
  PRODUCT_STATUS,
  PRODUCT_STATUS_VALUES,
  CUSTOMER_PRODUCT_STATUS,
  WAREHOUSE_TYPE,
  WAREHOUSE_TYPE_VALUES,
  ORDER_STATUS,
  ORDER_STATUS_VALUES,
  STAFF_ORDER_UPDATE_STATUS_VALUES,
  ORDER_STATUS_TRANSITIONS,
  TRANSFER_STATUS,
  TRANSFER_STATUS_VALUES,
  SHIFT_STATUS,
  SHIFT_STATUS_VALUES,
  ORDER_PAYMENT_METHOD,
  ORDER_PAYMENT_METHOD_VALUES,
  POS_PAYMENT_METHOD,
  POS_PAYMENT_METHOD_VALUES,
  PAYMENT_METHOD,
  PAYMENT_METHOD_VALUES,
  PAYMENT_STATUS,
  PAYMENT_STATUS_VALUES,
  WAREHOUSE_TRANSACTION_TYPE,
  PRODUCT_AVAILABILITY_FILTERS,
};