const ROLES = {
  SYSTEM_ADMIN:      'SYSTEM_ADMIN',
  WAREHOUSE_MANAGER: 'WAREHOUSE_MANAGER',
  STORE_MANAGER:     'STORE_MANAGER',
  STAFF:             'STAFF',
  CUSTOMER:          'CUSTOMER',
};

const ROLE_VALUES = Object.values(ROLES);

const STAFF_MANAGEMENT_ROLE_VALUES = [
  ROLES.STAFF,
  ROLES.STORE_MANAGER,
  ROLES.WAREHOUSE_MANAGER,
];

const ADMIN_PORTAL_ROLE_VALUES = [
  ROLES.SYSTEM_ADMIN,
  ROLES.STORE_MANAGER,
  ROLES.WAREHOUSE_MANAGER,
];

const BACKOFFICE_ROLE_VALUES = [
  ROLES.STAFF,
  ROLES.STORE_MANAGER,
  ROLES.SYSTEM_ADMIN,
];

const STORE_MANAGEMENT_ROLE_VALUES = [
  ROLES.SYSTEM_ADMIN,
  ROLES.STORE_MANAGER,
];

const INVENTORY_ACCESS_ROLE_VALUES = [
  ROLES.SYSTEM_ADMIN,
  ROLES.WAREHOUSE_MANAGER,
  ROLES.STORE_MANAGER,
  ROLES.STAFF,
];

const ORDER_ACCESS_ROLE_VALUES = [
  ROLES.CUSTOMER,
  ROLES.STAFF,
  ROLES.STORE_MANAGER,
  ROLES.SYSTEM_ADMIN,
];

const TRANSFER_ACCESS_ROLE_VALUES = [
  ROLES.SYSTEM_ADMIN,
  ROLES.WAREHOUSE_MANAGER,
  ROLES.STORE_MANAGER,
];

const TRANSFER_APPROVAL_ROLE_VALUES = [
  ROLES.SYSTEM_ADMIN,
  ROLES.WAREHOUSE_MANAGER,
];

module.exports = {
  ROLES,
  ROLE_VALUES,
  STAFF_MANAGEMENT_ROLE_VALUES,
  ADMIN_PORTAL_ROLE_VALUES,
  BACKOFFICE_ROLE_VALUES,
  STORE_MANAGEMENT_ROLE_VALUES,
  INVENTORY_ACCESS_ROLE_VALUES,
  ORDER_ACCESS_ROLE_VALUES,
  TRANSFER_ACCESS_ROLE_VALUES,
  TRANSFER_APPROVAL_ROLE_VALUES,
};